name: Create Firmware with AmneziaWG

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Firmware v${{ matrix.build_env.tag }} :: ${{ matrix.build_env.target }}/${{ matrix.build_env.subtarget }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_env:
          - tag: "23.05.3"
            pkgarch: aarch64_cortex-a53
            target: mediatek
            subtarget: filogic

    steps:
      - uses: actions/checkout@v4
        with:
          repository: openwrt/openwrt
          ref: v${{ matrix.build_env.tag }}
          fetch-depth: 0

      - name: Prepare feeds
        run: |
          wget https://downloads.openwrt.org/releases/${{ matrix.build_env.tag }}/targets/${{ matrix.build_env.target }}/${{ matrix.build_env.subtarget }}/feeds.buildinfo -O feeds.conf
          echo "src-git awgopenwrt https://github.com/yury-sannikov/awg-openwrt.git" >> feeds.conf
          ./scripts/feeds update -a && ./scripts/feeds install -a

      - name: Setup config
        run: |
          wget https://downloads.openwrt.org/releases/${{ matrix.build_env.tag }}/targets/${{ matrix.build_env.target }}/${{ matrix.build_env.subtarget }}/config.buildinfo -O .config
          
          echo "CONFIG_PACKAGE_kmod-amneziawg=y" >> .config
          echo "CONFIG_PACKAGE_amneziawg-tools=y" >> .config
          echo "CONFIG_PACKAGE_luci-app-amneziawg=y" >> .config
          echo "CONFIG_PACKAGE_kmod-crypto-lib-chacha20=y" >> .config
          echo "CONFIG_PACKAGE_kmod-crypto-lib-chacha20poly1305=y" >> .config
          echo "CONFIG_PACKAGE_kmod-crypto-chacha20poly1305=y" >> .config
          
          make defconfig

      - name: Build full firmware
        run: |
          make -j$(nproc)

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-firmware-${{ matrix.build_env.tag }}
          path: bin/targets/${{ matrix.build_env.target }}/${{ matrix.build_env.subtarget }}/
