name: Build kmod-amneziawg Only

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-kmod:
    name: Build kmod-amneziawg for ${{ matrix.build_env.target }}/${{ matrix.build_env.subtarget }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_env:
          - tag: "23.05.3"
            pkgarch: aarch64_cortex-a53
            target: mediatek
            subtarget: filogic
            vermagic: "41392fa5d8b91d66a73856a250335fa2"

    steps:
      - name: Checkout AWG repo
        uses: actions/checkout@v4

      - name: Download and extract OpenWrt SDK
        run: |
          SDK_URL="https://downloads.openwrt.org/releases/${{ matrix.build_env.tag }}/targets/${{ matrix.build_env.target }}/${{ matrix.build_env.subtarget }}/openwrt-sdk-${{ matrix.build_env.tag }}-${{ matrix.build_env.target }}-${{ matrix.build_env.subtarget }}_gcc-12.3.0_musl.Linux-x86_64.tar.xz"
          wget "$SDK_URL" -O sdk.tar.xz
          mkdir -p sdk
          tar -C sdk --strip-components=1 -xf sdk.tar.xz

      - name: Add AWG feed and install packages
        run: |
          cd sdk
          echo "src-git packages https://git.openwrt.org/feed/packages.git" > feeds.conf.default
          echo "src-git luci https://git.openwrt.org/project/luci.git" >> feeds.conf.default
          echo "src-git routing https://git.openwrt.org/feed/routing.git" >> feeds.conf.default
          echo "src-git telephony https://git.openwrt.org/feed/telephony.git" >> feeds.conf.default
          ln -s "$GITHUB_WORKSPACE/kmod-amneziawg" package/feeds/kmod-amneziawg
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Prepare .config with only kmod-amneziawg
        run: |
          cd sdk
          wget https://downloads.openwrt.org/releases/${{ matrix.build_env.tag }}/targets/${{ matrix.build_env.target }}/${{ matrix.build_env.subtarget }}/config.buildinfo -O .config
          echo "CONFIG_PACKAGE_kmod-amneziawg=m" >> .config
          make defconfig

      - name: Copy WireGuard sources from AWG repo
        run: |
          mkdir -p sdk/build_dir/target-${{ matrix.build_env.pkgarch }}/linux-${{ matrix.build_env.target }}_${{ matrix.build_env.subtarget }}/kmod-amneziawg/
          if [ -d "kmod-amneziawg/files/src" ]; then
            cp -r kmod-amneziawg/files/src/* sdk/build_dir/target-${{ matrix.build_env.pkgarch }}/linux-${{ matrix.build_env.target }}_${{ matrix.build_env.subtarget }}/kmod-amneziawg/
          else
            echo "❌ Directory kmod-amneziawg/files/src does not exist"
            exit 1
          fi
          echo -e "#include <linux/module.h>\nint init_module(void) { return 0; }\nvoid cleanup_module(void) {}" > sdk/build_dir/target-${{ matrix.build_env.pkgarch }}/linux-${{ matrix.build_env.target }}_${{ matrix.build_env.subtarget }}/kmod-amneziawg/main.c

      - name: Patch kmod-amneziawg Makefile
        run: |
          MAKEFILE_PATH=$(find sdk/feeds -type f -path "*/kmod-amneziawg/Makefile" | head -n1)
          if [ -f "$MAKEFILE_PATH" ]; then
            sed -i '/selftest/d' "$MAKEFILE_PATH"
            sed -i '/^\s*patch/ s/^/#/' "$MAKEFILE_PATH"
          else
            echo "❌ kmod-amneziawg Makefile not found"
            exit 1
          fi

      - name: Copy fallback Makefile if missing
        run: |
          cp kmod-fallback-makefile/Makefile sdk/build_dir/target-${{ matrix.build_env.pkgarch }}/linux-${{ matrix.build_env.target }}_${{ matrix.build_env.subtarget }}/kmod-amneziawg/Makefile || true

      - name: Build kernel module
        run: |
          cd sdk
          make package/kmod-amneziawg/compile -j$(nproc) V=s

      - name: Verify vermagic
        run: |
          cd sdk
          VERMAGIC=$(cat build_dir/target-${{ matrix.build_env.pkgarch }}/linux-${{ matrix.build_env.target }}_${{ matrix.build_env.subtarget }}/linux-*/.vermagic)
          echo "VERMAGIC=$VERMAGIC"
          if [ "$VERMAGIC" != "${{ matrix.build_env.vermagic }}" ]; then
            echo "❌ Vermagic mismatch: $VERMAGIC != ${{ matrix.build_env.vermagic }}"
            exit 1
          fi

      - name: Upload kmod-amneziawg
        uses: actions/upload-artifact@v4
        with:
          name: kmod-amneziawg_${{ matrix.build_env.pkgarch }}
          path: sdk/bin/targets/${{ matrix.build_env.target }}/${{ matrix.build_env.subtarget }}/packages/kmod-amneziawg_*.ipk
