name: Build kmod-amneziawg Only

on:
  workflow_dispatch:

jobs:
  build:
    name: Build kmod-amneziawg for mediatek/filogic
    runs-on: ubuntu-latest

    steps:
      - name: Checkout AWG repo
        uses: actions/checkout@v4

      - name: Download and extract OpenWrt SDK
        run: |
          export SDK_URL="https://downloads.openwrt.org/releases/23.05.3/targets/mediatek/filogic/openwrt-sdk-23.05.3-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64.tar.xz"
          echo "Downloading SDK from $SDK_URL"
          wget "$SDK_URL" -O sdk.tar.xz
          mkdir sdk
          tar -xf sdk.tar.xz -C sdk --strip-components=1

      - name: Add AWG feed and install packages
        run: |
          echo "src-git awgopenwrt https://github.com/yury-sannikov/awg-openwrt.git" >> sdk/feeds.conf
          cd sdk
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Prepare .config with only kmod-amneziawg
        run: |
          cd sdk
          echo "CONFIG_PACKAGE_kmod-amneziawg=m" > .config
          make defconfig

      - name: Build kernel module
        run: |
          cd sdk
          make package/kmod-amneziawg/compile -j$(nproc) V=s

      - name: Verify vermagic
        run: |
          VERMAGIC_BUILT=$(cat sdk/build_dir/target-*/linux-*/linux-*/.vermagic)
          echo "Built vermagic: $VERMAGIC_BUILT"
          if [[ "$VERMAGIC_BUILT" != "41392fa5d8b91d66a73856a250335fa2" ]]; then
            echo "Vermagic mismatch! Expected 41392fa5d8b91d66a73856a250335fa2"
            exit 1
          fi

      - name: Upload kmod-amneziawg
        uses: actions/upload-artifact@v4
        with:
          name: kmod-amneziawg-ipk
          path: sdk/bin/targets/*/*/packages/kmod-amneziawg_*.ipk
